package es.osalguero.tiendaelect.gui.view.enumeration;

public enum VistasEnum {

	VISTA_CARGA_DATOS, VISTA_LOGIN, VISTA_PRINCIPAL, VISTA_LISTADO_CLIENTES, 
	VISTA_NUEVO_CLIENTE, VISTA_LISTADO_VENTAS, VISTA_NUEVA_VENTA, VISTA_EXCEPTION;
	
}
