package es.osalguero.tiendaelect.gui.view.enumeration;

public enum VistasEnum {

	VISTA_CARGA_DATOS, 
    VISTA_LOGIN, 
    VISTA_PRINCIPAL,
    VISTA_EXCEPTION,
    VISTA_CONFIGURACION,
    VISTA_LISTADO_EMPLEADOS, 
    VISTA_EDICION_EMPLEADO,
	VISTA_LISTADO_CLIENTES,
	VISTA_EDICION_CLIENTE,
	VISTA_LISTADO_VENTAS,
	VISTA_LISTADO_PRODUCTOS;
	
}
