package es.osalguero.tiendaelect.modelo;

public enum Propiedades {

	FICHERO_TIENDA,
	FICHERO_PRODUCTOS,
	FICHERO_EMPLEADOS,
	FICHERO_CLIENTES,
	FICHERO_VENTAS,
	FICHERO_DEVOLUCIONES,
	FICHERO_REPARACIONES,
	FICHERO_FINANCIACIONES;
}
